service: skaityta

image: daliusd1982/skaityta

servers:
  web:
    - 195.201.143.78

proxy:
  ssl: true
  hosts:
    - skaityta.lt
    - www.skaityta.lt
  app_port: 3000

registry:
  username: daliusd1982

  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    DATA_PATH: /data

accessories:
  data:
    roles:
      - web
    directories:
      data:/data
